spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/goldenratio
    username: sa
    password: 'sa'
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
mvc:
  path match:
    matching-strategy: ant_path_matcher

logging.level:
  org.hibernate.SQL: debug

jwt:
  secret: "goldenratiosecretKey"


server:
  servlet:
    encoding:
      charset: UTF-8